name: 0.1.$(Rev:r)

trigger:
  batch: true
  paths:
    include:
      - parrot
  branches:
    include:
      - master

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self
            fetchDepth: 1

          - task: DotNetCoreCLI@2
            displayName: 'Run Unit Tests'
            inputs:
              command: 'test'
              projects: 'parrot/tests/parrot.UnitTests/parrot.UnitTests.csproj'
              arguments: '--configuration $(BuildConfiguration) --logger:trx'
              testRunTitle: 'Unit Tests'

          - task: DotNetCoreCLI@2
            displayName: 'Publish Application'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: 'parrot/src/parrot/parrot.csproj'
              arguments: '--configuration $(BuildConfiguration) --output dist'
              zipAfterPublish: false
              modifyOutputPath: false

        