name: 0.1.$(Rev:r)

trigger:
  batch: true
  paths:
    include:
      - parrot/src/parrot/charts
      - parrot/azure-pipelines.helm.yaml
    exclude:
      - parrot/azure-pipelines.deploy.yml
  branches:
    include:
      - master

variables:
  - group: acr
  - name: helmVersion
    value: 3.0.2
  - name: buildConfiguration
    value: 'Release'
  - name: containerRepository
    value: parrot
  - name: nuget_packages
    value: $(Pipeline.Workspace)/.nuget/packages

stages:
  - stage: Build
    displayName: 'Package Helm Chart'
    jobs:
      - job: Helm
        displayName: 'Build and Push Helm Chart'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self
            fetchDepth: 1

          - task: HelmInstaller@1
            displayName: 'Initialize Helm'
            inputs:
              helmVersionToInstall: '$(helmVersion)'

          - task: HelmDeploy@0
            displayName: 'Package Helm Chart'
            inputs:
              command: 'package'
              chartPath: 'parrot/src/parrot/charts/parrot'
              chartVersion: '$(Build.BuildNumber)'
              save: false

          - task: AzureCLI@2
            displayName: 'Push Helm Chart'
            inputs:
              azureSubscription: 'Azure'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az acr helm push \
                  --name $(CONTAINER_REGISTRY_NAME) \
                  $(Build.ArtifactStagingDirectory)/$(containerRepository)-$(Build.BuildNumber).tgz
